### ISSUE TITLE
[Question]S3 usage

### ISSUE THREAD

**Issue by gmkbenjamin** [certau/ir2go#1]
Hello,
I was wondering if there are any particular reason as to why S3 is used instead of other providers or having the files on the local computer?

**Comment by birdman4512** [comment]
Hi gmkbenhamin.

No particular reason for choosing S3 over any other provider. There are many options available to host the files, however I was looking for something that provide authentication, easily accessible from within PowerShell (Which S3 is once the AWS module is imported)

In relation to local files, this was also considered, however was avoided as I wanted the environment to be able to be built easily even when out of the office and potentially out of hours (i.e. it would be difficult to get the local files for deployment)
